### ISSUE TITLE
FortiOS 6.0 compatibility?

### ISSUE THREAD

**Issue by javcasalc** [fortinet-solutions-cse/ansible_generator#1]
Hi, 

is this code compatible with FortiOS 6.0? I'm getting this error:

```
Traceback (most recent call last):
  File "./generate.py", line 103, in <module>
    render_module(fgt_sch_results[69], fgt_schema['version'])
IndexError: list index out of range
```

I've got my json schema from 
```
/api/v2/monitor/firewall/policy/?vdom=VDOM1
```

**Comment by thomnico** [comment]
fgt_schema will not work on the monitoring API 5.6 or 6.0.

After that please send information allowing me to reproduce and not assume I see your code and understand what you try to achieve.

**Comment by javcasalc** [comment]
I have a cluster of FGT-500E with 6.0.2, and I'd like to start working on generation of ansible playbooks to manage the current and future config changes. So I did a first test, with this API query:
```
/api/v2/cmdb/firewall/policy/?vdom=VDOM1
```
I saved the json schema and run generate.py later

That's all I tried :)

**Comment by mamunozgonzalez** [comment]
Hi @javcasalc,
 thanks for trying out our generator. It is intended to work with the full schema of the FGT. Currently it has been tested with v6.0.2. 
In order to get the full schema please use this request:

GET http://{{fgt_ip}}/api/v2/cmdb?action=schema

You can see the output generated in:
https://github.com/fortinet-solutions-cse/ansible_fgt_modules

However I need to update them since there has been a couple of changes in the generator that will slightly change the output.

Btw, this is a work in progress and not all generated modules have been tested so far. You can guess which ones are already working by looking at the examples in:

https://github.com/fortinet-solutions-cse/ansible_generator/tree/master/examples

Meaning, if there is an example, the corresponding module has been tested with it. Note there are usually files to create and remove items.

Let me know if you need further info.

**Comment by javcasalc** [comment]
Hi @mamunozgonzalez 

I tried with 
```
GET http://{{fgt_ip}}/api/v2/cmdb?action=schema
```
and now generate.py is doing its job:
```
> ./generate.py                                                
File generated: output/v6.0.2/fortios_system_ipv6_tunnel.py
File generated: output/v6.0.2/fortios_system_ipv6_tunnel_example.yml

Parsing schema:
Module name: system_vdom
Iteration:0, Schema position: 0
File generated: output/v6.0.2/fortios_system_vdom.py
File generated: output/v6.0.2/fortios_system_vdom_example.yml
........
```

but all files look to be "examples".....not playbook customized with running configuration from fgt_schema ....is it correct?

**Comment by mamunozgonzalez** [comment]
Good. It seems you got it working properly.
The output seems to be correct: Every table of the schema (e.g. system/ipv6_tunnel or firewall/policy) generates a couple of files: 
The first one: fortios_system_ipv6_tunnel.py is an Ansible module that allows the user to modify system/ipv6_tunnel configuration of a FortiGate . You need a playbook (see next file) that will make use of this Ansible module. 
The second one: fortios_system_ipv6_tunnel_example.yml is a draft of an example that makes use of the previous Ansible module generated. This file will call fortios_system_ipv6_tunnel module to change the system/ipv6_tunnel configuration of a Fortigate.

In both cases there is no running configuration stored. The fortigate schema does not keep current configuration or operational status, it is just an schema of the data that you can find on any FortiGate.

Hope that helps.

**Comment by javcasalc** [comment]
ok, got it!!

Thanks!
