### ISSUE TITLE
Feature request: Allow additional documentation

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_generator#10]
It would be convenient if there were some way to add additional documentation.

Perhaps, when the generator runs, it could parse another directory to see if there's a documentation file there, and include that first before your existing documentation. This means that documentation can be improved, without preventing the automatic construction of revised modules.

One way to possibly do this would be to have something akin to the following statement (perhaps around [this line](https://github.com/fortinet-solutions-cse/ansible_generator/blob/33b56c4dca982e8dafa878e69496d5c1d6e76cb6/ansible_templates/examples.j2#L26)):
```
{% set documentation = 'extra_docs/' + module_name + '.j2' %}
{% include documentation ignore missing %}
```

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy 
thanks for the suggestion. I think it can be a nice improvement. Actually we think a similar mechanism for generated code would be also needed at some point in the future, because there can always be exceptions that need to be addressed with a particular piece of code that cannot be automated. 

We'll keep it in the backlog as a nice improvement.

**Comment by mamunozgonzalez** [comment]
Closing as this is handled now in a forked repository (see README) with new mechanisms for documentation. This repo will be archived.
