### ISSUE TITLE
Feature request: Login failure returns an exception, and should be caught and handled

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_generator#9]
Perhaps at [this line which says "fos.login"](https://github.com/fortinet-solutions-cse/ansible_generator/blob/607590e5ba69410c37113bd2a056d7fcf7cd10d6/ansible_templates/code.jinja#L16) you could do a try/catch and do some error checking on the response from the FortiOSAPI to see whether it's a "Failed to login" or "No response from server"?

**Comment by JonTheNiceGuy** [comment]
(Just to note, this has been raised because I spent about an hour looking for HTTPS errors which are usually hidden by the code when you *don't* have invalid login details for a box, but it was a username/password error that then starts showing "you have an invalid certificate error" etc...)

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy ,
 soon we are submitting for review the new HTTPAPI plugin for handling connectivity in our modules, as requested by Ansible.
Localhost connection is deprecated and will be removed in the next months/years to comply with Ansible requests.

In the new HTTPAPI plugin this issue is addressed, please feel free to re-check once it is released to the public (a preview is available in this repo already). 
This HTTPAPI plugin will be submitted shortly in the next days (it's already finished and we are creating a PR for Ansible now).
